//
// Created by Wang, Yuyang on 19/03/2023.
//

#ifndef ADVANCED_PROGRAMMING_GROUP_DIJKSTRA_PROJECTION_H
#define ADVANCED_PROGRAMMING_GROUP_DIJKSTRA_PROJECTION_H


class Projection {

};


#endif //ADVANCED_PROGRAMMING_GROUP_DIJKSTRA_PROJECTION_H
