//
// Created by Wang, Yuyang on 19/03/2023.
//

#ifndef ADVANCED_PROGRAMMING_GROUP_DIJKSTRA_SLICE_H
#define ADVANCED_PROGRAMMING_GROUP_DIJKSTRA_SLICE_H


class Slice {

};


#endif //ADVANCED_PROGRAMMING_GROUP_DIJKSTRA_SLICE_H
